parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/DTO/'
            - '../src/Kernel.php'

    App\ArgumentResolver\EntityResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 100 }

    App\ArgumentResolver\QueryParamResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 100 }
